=== akuchynski/LibraryXML/library-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xns:schema xmlns:xns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.it-academy.by/library-schema" xmlns:itacby="http://www.it-academy.by/library-schema"
	elementFormDefault="qualified">

	<xns:element name="publications">
		<xns:complexType>
			<xns:sequence maxOccurs="unbounded">
				<xns:element name="publication" type="itacby:publication_type" />
			</xns:sequence>
		</xns:complexType>
	</xns:element>

	<xns:complexType name="publication_type">
		<xns:sequence>
			<xns:choice>
				<xns:element name="book" />
				<xns:element name="magazine" />
				<xns:element name="newspaper" />
			</xns:choice>
			<xns:element name="count" type="xns:int" />
			<xns:element name="title" type="xns:string" />
			<xns:element name="year" type="xns:int" />
			<xns:element name="authors" type="itacby:authors_type" minOccurs="0" />
			<xns:choice>
				<xns:element name="reading-room" />
				<xns:element name="home" type="itacby:home_type" />
			</xns:choice>
		</xns:sequence>
		<xns:attribute name="id" />
	</xns:complexType>

	<xns:complexType name="authors_type">
		<xns:sequence maxOccurs="unbounded">
			<xns:element name="author" type="itacby:author_type" />
		</xns:sequence>
	</xns:complexType>

	<xns:complexType name="author_type">
		<xns:sequence>
			<xns:element name="name" type="xns:string" />
			<xns:element name="surname" type="xns:string" />
		</xns:sequence>
	</xns:complexType>

	<xns:complexType name="home_type">
		<xns:sequence>
			<xns:element name="date" type="xns:int" />
		</xns:sequence>
	</xns:complexType>
</xns:schema>

=== akuchynski/LibraryXML/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<publications xmlns="http://www.it-academy.by/library-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.it-academy.by/library-schema library-schema.xsd">

	<publication id="1">
		<book />
		<count>2</count>
		<title>Book1</title>
		<year>1568</year>
		<authors>
			<author>
				<name>AuthorName1</name>
				<surname>AuthorSurname1</surname>
			</author>
		</authors>
		<reading-room />
	</publication>

	<publication id="2">
		<book />
		<count>12</count>
		<title>Book2</title>
		<year>1902</year>
		<authors>
			<author>
				<name>AuthorName2</name>
				<surname>AuthorSurname2</surname>
			</author>
			<author>
				<name>AuthorName3</name>
				<surname>AuthorSurname3</surname>
			</author>
		</authors>
		<home>
			<date>21</date>
		</home>
	</publication>

	<publication id="3">
		<magazine />
		<count>22</count>
		<title>Magazine1</title>
		<year>1999</year>
		<reading-room />
	</publication>

</publications>

=== akuchynski/LibraryXML/resources/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<publications xmlns="http://www.it-academy.by/library-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.it-academy.by/library-schema library-schema.xsd">

	<publication id="1">
		<book />
		<count>2</count>
		<title>Book1</title>
		<year>1568</year>
		<authors>
			<author id="1">
				<name>AuthorName1</name>
				<surname>AuthorSurname1</surname>
			</author>
		</authors>
		<reading-room />
	</publication>

	<publication id="2">
		<book />
		<count>12</count>
		<title>Book2</title>
		<year>1902</year>
		<authors>
			<author id="2">
				<name>AuthorName2</name>
				<surname>AuthorSurname2</surname>
			</author>
		</authors>
		<home>
			<date>21</date>
		</home>
	</publication>

	<publication id="3">
		<book />
		<count>22</count>
		<title>Book3</title>
		<year>1999</year>
		<authors>
			<author id="3">
				<name>AuthorName3</name>
				<surname>AuthorSurname3</surname>
			</author>
		</authors>
		<reading-room />
	</publication>

</publications>
